data:
  target: nerf.data.blender_dataset.BlenderPrecropRayDataset
  params: 
    basedir: 'data/nerf_synthetic/lego'
    factor: 2
    skip: 1
    white_bkgd: True
  train:
    precrop:
      precrop_frac: 0.5
      N_rand: 4096
    dataloader_params:
      batch_size: 1024
      shuffle: True
      num_workers: 8
  test:
    dataloader_params:
      batch_size: 1024
      shuffle: False
      num_workers: 8
  val:
    other_params:
      batch_size: 1024
      count: 1


model_coarse:
  target: nerf.models.nerf.NeRF
  params:
    D: 8
    W: 256
    input_ch: 3
    input_ch_views: 3
    skips: [4]
    multires: 10
    multires_views: 4
    raw_noise_std: 0
    white_bkgd: True

model_fine:
  target: nerf.models.nerf.NeRF
  params:
    D: 8
    W: 256
    input_ch: 3
    input_ch_views: 3
    skips: [4]
    multires: 10
    multires_views: 4
    raw_noise_std: 0
    white_bkgd: True

render:
  target: nerf.modules.render.Render
  params:
    near: 2
    far: 6
    N_samples: 64
    N_importance: 128
    perturb: False

setting:
  device: 1
  logdir: logs/blender_paper_lego
  lr: 5e-4
  ckpt: logs/blender_paper_lego/200000.tar
  # ckpt: 
  step_num: 250000
  i_val: 10000
  precrop_iters: 500